### ISSUE TITLE
Viable approach to ST_LineSubString?

### ISSUE THREAD

**Issue by dblodgett-usgs** [r-spatial/lwgeom#16]
I worked up a decent approach (in that it seems quite fast working with >70k river features) to the same geometric function as ST_LineSubString over here: https://gist.github.com/dblodgett-usgs/cf87392c02d73f1b7d16153d2b66a8f3 It is written to orchestrate over an sf LINESTRING dataframe though. Some work would be required to boil it down to the basic function.

@edzer you told me to raise this here, but since it doesn't use lwgeom, (it's dplyr / sf) is it really appropriate? 

This function is pretty GIS - swiss army knife, but it would be good to have a ST_LineSubString function some place... fine to move on if this doesn't fit, but wanted to offer it up if it seems applicable.

**Comment by edzer** [comment]
I pointed you here because the PostGIS function with that name (most likely) uses [this](https://github.com/r-spatial/lwgeom/blob/master/src/liblwgeom/ptarray.c#L1055). It should be fairly trivial to incorporate that into lwgeom, which interfaces this library.

**Comment by dblodgett-usgs** [comment]
Cool! I'll test this out soon.

**Comment by dblodgett-usgs** [comment]
Dang. Nice. That was quick!! 

Somebody else can create an apply-like function where I wrote a dumb loop, but this works pretty good as far as I can tell.

```
devtools::install_github("r-spatial/lwgeom")
geojson <- '{
"type": "FeatureCollection",
"name": "sample",
"features": [
{ "type": "Feature", "properties": { "ID": 1 }, "geometry": { "type": "LineString", "coordinates": [ [ -122.916097119649635, 38.229575873993497 ], [ -122.916154986316201, 38.229346873993904 ], [ -122.916676986315338, 38.228614207328235 ], [ -122.917430786314128, 38.227148873997294 ], [ -122.917488319647418, 38.226210273998674 ], [ -122.917371986314322, 38.22579827399926 ], [ -122.917400319647584, 38.224516407334704 ], [ -122.918995719645125, 38.223348274003115 ], [ -122.920127119643382, 38.223004607336975 ], [ -122.921171719641791, 38.222546407337802 ], [ -122.922186919640126, 38.221950807338601 ], [ -122.922795786305926, 38.221286674006421 ] ] } }
]
}'
sf <- sf::st_transform(sf::st_read(geojson), 5070)
split <- lwgeom::st_linesubstring(sf$geometry[[1]], 0, (1/3))
plot(sf$geometry[[1]], col="red")
plot(split, col = "blue", add = TRUE)

out_spec <- data.frame(ID = c(1,1,1), newID = c(1, 2, 3), start = c(0, (1/3), (2/3)), end = c((1/3), (2/3), (1)))

out_geo <- list()

for (i in 1:nrow(out_spec)) {
  out_geo[[out_spec$newID[i]]] <- lwgeom::st_linesubstring(sf$geometry[out_spec$ID[i]], out_spec$start[i], out_spec$end[i])[[1]]
}

out <- sf::st_sf(out_spec, sf::st_sfc(out_geo))

plot(dplyr::select(out, newID))
```
![screen shot 2018-03-07 at 2 21 58 pm](https://user-images.githubusercontent.com/1492803/37117105-e3d57df2-2215-11e8-8be1-f36b6c91ffe7.png)

![screen shot 2018-03-07 at 2 42 30 pm](https://user-images.githubusercontent.com/1492803/37117097-e0666e2e-2215-11e8-9c8f-9bbba2ea18b4.png)
