### ISSUE TITLE
Enable GitHub Pages

### ISSUE THREAD

**Issue by krlmlr** [r-spatial/lwgeom#18]
at https://r-spatial.github.io/lwgeom. The reference in `docs/` looks good.

**Comment by edzer** [comment]
Thanks!

**Comment by edzer** [comment]
Like, in the README.md?

**Comment by krlmlr** [comment]
Next to the repo description "bindings to the liblwgeom library". It would be also great to add tags like "r" "spatial" "gis" etc.

For the README I'd have sent a PR ;-)
