### ISSUE TITLE
Support of splitting a polygon by a MultiLineString

### ISSUE THREAD

**Issue by raff-k** [r-spatial/lwgeom#20]
**Is it possible or planed to integrate a function that can split a polygon by a MultiLineString?**

My idea is to split a polygon into n-parts of equal areas. To get the corresponding lines, at the moment, I use the optim-function, which minimize the squared sum of the area deviation between the original polygon and its splitted parts ([the function](https://github.com/raff-k/Lslide/blob/master/R/dividePolygon.R)).
So far, the splitting is conducted by (1) creation of lines, (2) buffer lines and (3) calculate the difference between the polygon and the buffered lines (example code below). However, the method has the drawback that (1) the resulted splitted polygons do not intersect anymore, and (2) if I buffer the splitted polygon, they are larger than the orignal polygon and are of course overlapping.

```r
# create polygon
pol <- rbind(c(-3,3), c(-3,4), c(-2,4), c(-2,3), c(-3,3))
pol <- sf::st_polygon(list(pol)) %>% st_sfc(.)

# create multilinestring
mls <- st_multilinestring(list(rbind(c(-2.5, 3), c(-2.6, 4)), rbind(c(-2.8, 3), c(-2.9, 4))))

# buffer line to get thin polygons
mls.buf <- sf::st_buffer(x = mls, dist = 0.000001)  # create a very thin polygon


## splitting
# calculate the differences of polygons and casting
pol.dif <- sf::st_difference(x = pol, y = mls.buf) %>%  sf::st_cast(x = ., to = "POLYGON")

# plot result
plot(pol.dif)


## check intersection
sf::st_intersects(pol.dif)
# Sparse geometry binary predicate list of length 3, where the predicate was `intersects'
#  1: 1
#  2: 2
#  3: 3

# -> polygons do not intersect each other



## check intersection using same buffer size
sf::st_buffer(x = pol.dif, dist = 0.000001000001) %>% sf::st_intersects(.)
# Sparse geometry binary predicate list of length 3, where the predicate was `intersects'
# 1: 1, 2
# 2: 1, 2, 3
# 3: 2, 3

# -> now, polygons do intersect each other but have a different overall area

pol.dif.comb <- sf::st_buffer(x = pol.dif, dist = 0.000001000001) %>% 
  sf::st_combine(.)

identical(sf::st_area(x = pol.dif.comb), sf::st_area(x = pol))
# FALSE
```

**Comment by edzer** [comment]
You can use `lwgeom::st_split`, but it only splits polygons by `LINESTRING`s:
```r
> st_split(st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,1), c(0,0)))), st_linestring(rbind(c(-1,0.5), c(3, 0.5))))
GEOMETRYCOLLECTION (POLYGON ((1 0.5, 1 0, 0 0, 0 0.5, 1 0.5)), POLYGON ((0 0.5, 0 1, 1 1, 1 0.5, 0 0.5)))
```
