### ISSUE TITLE
create st_endpoint

### ISSUE THREAD

**Issue by Robinlovelace** [r-spatial/lwgeom#27]
See #22

**Comment by Robinlovelace** [comment]
I'll give this one a go.

**Comment by edzer** [comment]
Is this moving, or time to close?

**Comment by Robinlovelace** [comment]
It's stalled, along with my C++ skills. There is one beacon of hope though: @virgesmith offered to help me with this. You up for a ~1hr session on this Andrew? If we cannot bosh it by Friday, I'd say close it. Thanks for your patience with this.

**Comment by Robinlovelace** [comment]
- Friday next week I meant.

**Comment by virgesmith** [comment]
@Robinlovelace I'm around next week so lets combine this with a run (if the snow melts) and some lunch

**Comment by Robinlovelace** [comment]
Thursday any good? Tuesday is teaching day now.

**Comment by virgesmith** [comment]
@Robinlovelace I've given you permish write on https://github.com/virgesmith/lwgeom, I've done the C++ side of things dunno what you had in mind re: examples/doc/tests, but feel free to commit and then PR

**Comment by Robinlovelace** [comment]
Many thanks @virgesmith, awesome C++ boshing sir!
