### ISSUE TITLE
support st_geohash directly parse polygon

### ISSUE THREAD

**Issue by harryprince** [r-spatial/lwgeom#33]
I am using st_geohash to parse a sf polygon data frame into geohash list, however, I found it fail to convert polygons to geohash list directly.

**Comment by edzer** [comment]
Could you please give a reproducible example?

**Comment by harryprince** [comment]
sorry, I found a alternative way:

s_df %>%
sf::st_make_grid(cellsize = .00001) %>% 
sf::st_intersection(s_df) %>% 
lwgeom::st_geohash(9)
