### ISSUE TITLE
error: geos_c.h not found in given locations

### ISSUE THREAD

**Issue by veioenza** [r-spatial/lwgeom#34]
git clone https://github.com/r-spatial/lwgeom.git
R CMD INSTALL --configure-args="--with-proj-include=/local/software/proj/5.2.0/include --with-proj-lib=/local/software/proj/5.2.0/lib" lwgeom

gives, 

checking for geos-config... /local/software/geos/3.7.0/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.7.0
checking GEOS version >= 3.3.0... yes
checking geos_c.h usability... no
checking geos_c.h presence... no
checking for geos_c.h... no
configure: error: geos_c.h not found in given locations.

Running /local/software/geos/3.7.0/bin/geos-config --includes

/local/software/geos/3.7.0/include

And /local/software/geos/3.7.0/bin/geos-config --clibs

-L/local/software/geos/3.7.0/lib -lgeos_c

**Comment by edzer** [comment]
Which platform is this on?

**Comment by edzer** [comment]
Oh and another question: did package sf install without problems?

**Comment by veioenza** [comment]
Platform is Redhat 6.10 because it is running on a cluster.
Both geos and proj are installed in none-default locations. 

sf installed fine with,
install.packages('sf', configure.args=c('--with-proj-include=/local/software/proj/5.2.0/include',
                                        '--with-proj-lib=/local/software/proj/5.2.0/lib'))

**Comment by veioenza** [comment]
I forked and could get past this message by explicitly adding,

CPPFLAGS="${CPPFLAGS} ${PKG_CPPFLAGS} ${GEOS_CPPFLAGS}"
LIBS="${LIBS} ${PKG_LIBS} ${GEOS_CLIBS}"

after the geos-config check, and in the conclusion phase

PKG_LIBS="${PKG_LIBS} ${PROJ_LIBS} ${GEOS_LIBS}"

./Configure then finishes but it gets a different linking error later on related to proj

/local/software/binutils/2.26/bin/ld: cannot find -lproj

Looking at the build command, it doesn't seem to have added the proj libraries. If I manually run the build command with -L/local/software/proj/5.2.0/lib the command completes fine.

**Comment by edzer** [comment]
@veioenza - could you pls check whether lwgeom 0.1-5, now on CRAN, does this correctly?
