### ISSUE TITLE
With or without liblwgeom

### ISSUE THREAD

**Issue by vvrably** [r-spatial/lwgeom#36]
In README.md, shouldn't the command for installation **without** liblwgeom preinstalled on Linux read as follows?
```
R CMD INSTALL --configure-args="--with-liblwgeom" lwgeom_VERSION.tar.gz
```

**Comment by edzer** [comment]
It should be something like `--with-liblwgeom-internal` as opposed to `--with-liblwgeom-system`, but this is all a background fight since future versions will only use the internal version; see also #30.

**Comment by vvrably** [comment]
Thanks, I was confused because R always tried to use the old preinstalled library.
