### ISSUE TITLE
Feature Request: ST_GeomFromGeoHash

### ISSUE THREAD

**Issue by edrubin** [r-spatial/lwgeom#37]
I'm wondering if it is possible to port/bring in `ST_GeomFromGeoHash`, since `lwgeom` already includes a nice way to geohash locations via `st_geohash()`. (The goal would be to be able to geohash and *un-geohash*.)

Thank you for your fantastic work on these projects.

**Comment by shermstats** [comment]
I'll second this feature request.  I'm currently working on a project where I'm working with geohashes and want to plot their geometry on a map.  This function would make my life much easier.

**Comment by edzer** [comment]
PR welcome!
