### ISSUE TITLE
Not compatible with sf package from conda defaults channel

### ISSUE THREAD

**Issue by ashki23** [r-spatial/lwgeom#46]
I am using the following to build my env:

```
conda create --yes --channel defaults --channel conda-forge --prefix ./my_env r-base r-sf r-lwgeom
```

Since `sf` and `r-base` are available in the defaults channel, they will download from the main channel and `lwgeom` comes from conda-forge. When I open R and use `library('lwgeom')` I will get the following error:

```
Error: package or namespace load failed for ‘lwgeom’ in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/home/my_env/lib/R/library/lwgeom/libs/lwgeom.so': libproj.so.15: cannot open shared object file: No such file or directory
``` 

File `libproj.so.13` is available in the above directory. I am using conda 4.5.12 on CentOS.

**Comment by edzer** [comment]
My best guess would be to check with the person maintaining the conda-forge lwgeom package - I've never touched conda so far, and have for instance no clue whether you are talking about the installation of a binary or a source package.
