### ISSUE TITLE
configure: error: neither proj.h nor proj_api.h were found.

### ISSUE THREAD

**Issue by mykmilligan** [r-spatial/lwgeom#49]
I having problems installing lwgeom for a CentOS 7.3 based HPC cluster. I'm using R 3.6.2 and the following:

R CMD INSTALL lwgeom_0.1-7.tar.gz --configure-args='--with-proj-lib=/source/directory/proj/5.2.0/lib --with-proj-include=/source/directory/proj/5.2.0/include --with-proj-share=/source/directory/proj/5.2.0/share/proj --with-geos-config=/source/directory/geos/3.6.3/bin/geos-config'

Error:

liblwgeom/lwgeom_geos.c:1079:10: error: ‘POSTGIS_GEOS_VERSION’ undeclared (first use in this function)
          POSTGIS_GEOS_VERSION);
          ^
liblwgeom/lwgeom_geos.c:1079:10: note: each undeclared identifier is reported only once for each function it appears in
make: *** [liblwgeom/lwgeom_geos.o] Error 1
ERROR: compilation failed for package ‘lwgeom’
* removing ‘/share/apps/gcc/4.8.5/R/3.6.2/lib64/R/library/lwgeom’

When I try the newer version of lwgeom:
R CMD INSTALL lwgeom_0.2-1.tar.gz --configure-args='--with-proj-lib=/source/directory/proj/6.1.1/lib --with-proj-include=/source/directory/proj/6.1.1/include/ --with-proj-share=/source/directory/proj/6.1.1/share/proj --with-geos-config=/source/directory/geos/3.6.3/bin/geos-config'

I get this error:
checking proj.h usability... no
checking proj.h presence... no
checking for proj.h... no
checking proj_api.h usability... no
checking proj_api.h presence... no
checking for proj_api.h... no
configure: error: neither proj.h nor proj_api.h were found.
ERROR: configuration failed for package ‘lwgeom’
* removing ‘/share/apps/gcc/4.8.5/R/3.6.2/lib64/R/library/lwgeom’

Do you have any suggestions for resolving these errors?

**Comment by edzer** [comment]
There is a new version of `lwgeom` on CRAN, please try that. If neither proj.h nor proj_api.h are found, you have a problem, also with the new version.

**Comment by mykmilligan** [comment]
I have tried lwgeom_0.1-7 and lwgeom_0.2-1.tar.gz. Each time I pointed to the proj files as listed above. Is there another way that I can point to the proj.h and proj_api.h when installing lwgeom?

**Comment by edzer** [comment]
I can confirm this.

**Comment by JonasGeschke** [comment]
having the same problem here ...

> error: neither proj.h nor proj_api.h were found.

would be great if you can help.

**Comment by edzer** [comment]
Please try again installing from github, the problem might have been solved.

**Comment by JonasGeschke** [comment]
...

> Error: Failed to install 'lwgeom' from GitHub:
(converted from warning) installation of package 'Rcpp' had non-zero exit status

also tried to install `Rcpp` from Github, doesnt work either.

**Comment by edzer** [comment]
OK, but that sounds like a problem with Rcpp, not lwgeom.

**Comment by JonasGeschke** [comment]
> OK, but that sounds like a problem with Rcpp, not lwgeom.

thats true.

**Comment by edzer** [comment]
@mykmilligan could you give this a try?
