### ISSUE TITLE
Issue when using lwgeom and shiny apps

### ISSUE THREAD

**Issue by lsturm2** [r-spatial/lwgeom#59]
Hello! I am trying to build and run a shiny app. It works locally on my machine, but when I try to deploy it to the Shiny servers, it gives me the error: "Warning: Error in join: lwgeom required: install first?" (A similar issue to this person: https://github.com/rstudio/shinyapps-package-dependencies/issues/241). I have tried multiple things such uninstalling and reinstalling lwgeom, using an older version of lwgeom, downloading from the github version, and turning off the dependency cache when building the shiny app. None of these approaches worked. After a quick google search, it seems like other people have been experiencing similar issues since about 26 days ago which seems like the last push. Do you have any ideas on how to fix this issue? Thank you!

**Comment by MarcosJCE** [comment]
Same here. `rsconnect::deployApp('myapp')` ends with `################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 739626514 failed: Error building image: Error building lwgeom (0.2-4). Build exited with non-zero status: 1`.

**Comment by Spswitzer** [comment]
edzer, I am not sure what it mean to add a commit, does this mean you think you have resolved the issue? I am experiencing the same error as the others in this thread. Please advise. Thank you for your efforts

**Comment by edzer** [comment]
I don't know - I know very little about shinyapps servers and how to configure them; I remember looking at this a few years ago, and completely forgot how things work there.

**Comment by Spswitzer** [comment]
Thanks for your quick response.

**Comment by aruberuku** [comment]
I am experiencing the same issue

This issue seems to have reappeared with the latest version.

Several posts have been made about it.
https://stackoverflow.com/questions/62165453/shiny-deployment-error-upgrade-geos-to-3-6-0-or-later-while-installing-package
https://stackoverflow.com/questions/62097231/upgrade-geos-version-on-shiny-apps-io/62165224
Some have had success downgrading
https://community.rstudio.com/t/shiny-app-no-longer-deploys-error-with-lwgeom/61708/7
But this does not work in my case, as well as for others

You help is greatly appreciated.

**Comment by edzer** [comment]
lwgeom 0.2-5 is now on CRAN, and should solve this.

**Comment by Spswitzer** [comment]
Thank you for your continued work to resolve this. I am not able to install version 0.2-5 from CRAN nor from Github. I can install 0.2-4 from CRAN, and I can see the upgrade to 0.2-5 available, but it will not successfully upgrade using R v. 4.0.0. When attempting to install from GitHub, I see the following errors for the units package Error: Failed to install 'lwgeom' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘units’
Error: Failed to install 'lwgeom' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘units’
I have uninstalled units, but still no success. 
Any additional guidance is appreciated.

**Comment by edzer** [comment]
What is your `sessionInfo()`?

**Comment by Spswitzer** [comment]
My session info follows: 
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.0 tools_4.0.0

**Comment by edzer** [comment]
Then either install rtools and compile lwgeom from source, or wait a few days more until CRAN has compiled an binary version and install that.

**Comment by Spswitzer** [comment]
Thank you!

**Comment by william3031** [comment]
Thanks for fixing it.

**Comment by edzer** [comment]
Thanks for the feedback!
