### ISSUE TITLE
LWGEOM installation fails with R-Studio

### ISSUE THREAD

**Issue by aloes2512** [r-spatial/lwgeom#81]
I use R-Studio 2022.07.1 with R 4.2.0 and tried to install lwgeon. I installed sf successful . But installation of lwgeon produces error message: "install of package `lwgeom` failed [error code 1].
This is because I need to understand the tutorial: "https://thinking-spatial.org/courses/angewandte_geodatenverarbeitung/kurs03/" which uses lwgeom for the examples

**Comment by edzer** [comment]
Please consult the course instructor first. 

You failed to specify your platform, the output of `sessionInfo()`, and the actual complete output you see after the installation failure.

**Comment by aloes2512** [comment]
Thank You for the fast response. In the mean time I tryed many things and something did help. Sorry, that I can not tell You, what solved the problem.
Kind regards
Alf Löffler 

Von meinem iPad gesendet
